baseURL = "https://www.ted027.com"
languageCode = "ja"
title = "行けたら行く"
theme = "mainroad"
paginate = "10"

disqusShortname = "ted027-com"
googleAnalytics = "UA-138367212-1"

pygmentsCodefences = true
pygmentsStyle = "mainroad"

[Author]
  name = "imait"
  bio = "横浜あたりでクラウドサービスをせこせこ開発しているエンジニァーです。"
  avatar = "/img/avatar.png"

[Params]
  subtitle = "野球と育児とコンピュータサイエンスのブログ"
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = true
  toc = true
  share = true
  mathjax = true
  post_navigation = true
  post_meta = ["popular", "date", "categories"] # Order of post meta information. Use ["none"] to turn off completely.
  #postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"]
  dateformat = "2006-01-02"
  customCSS = ["css/custom.css"]

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  # Enable widgets in given order
  widgets = ["ad_top", "search", "ad_second", "recent", "categories", "social", "ad_bottom"]

[Params.widgets]
  recent_num = 5
  tags_counter = false

[Params.widgets.social]
  twitter = "imaitt"
  github = "ted027"
  email = "imaitt0207@gmail.com"
  #facebook = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  #gitlab = "username"
  #bitbucket = "username"

# [outputs]
# home = [ "HTML", "AMP"]
# page = [ "HTML", "AMP"]