version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - run:
          name: update
          command: apk update && apk add git
      - checkout
      - run:
          name: build
          command: ./deploy.sh