version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/work
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:34:87:bd:d6:91:8b:25:22:32:04:16:30:88:c2:04"
      - run:
          name: install hugo
          command: |
            mkdir ~/src; cd $_
            # git clone https://github.com/gohugoio/hugo.git
            # cd hugo
            # go install -tags extended
            wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb -O hugo.deb
            sudo apt install ./hugo.deb
      - checkout
      - run:
          name: build
          command: |
            rm -rf public
            git clone git@github.com:ted027/ted027.github.io public
            hugo
      - run:
          name: push
          command: |
            cd public
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="rebuilding site `date`"
            git commit -m "$msg"
            git push origin master
  analytics:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/work
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:34:87:bd:d6:91:8b:25:22:32:04:16:30:88:c2:04"
      - run:
          name: analytics
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:ted027/blog
            cd blog/bin
            sudo pip install -r requirements.txt
            python googleanalytics.py
            cd -
      - run:
          name: push
          command: |
            cd blog
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="update popular posts `date`"
            git commit -m "$msg"
            git push origin master

workflows:
  version: 2
  normal_build:
    jobs:
      - build
  nightly_build:
    triggers:
      - schedule:
          cron: "10 15 * * 0,3"
          filters:
            branches:
              only:
                - master
    jobs:
      - analytics
