version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com
    steps:
      - checkout
      - run:
          name: update
          command: go get -v github.com/spf13/hugo
      - run:
          name: build
          command: ./deploy.sh