version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/work
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cb:6b:93:05:ca:cf:a7:50:16:bc:d2:cb:1e:a5:27:6b"
      - run:
          name: install hugo
          command: |
            mkdir ~/src; cd $_
            git clone https://github.com/gohugoio/hugo.git
            cd hugo
            go install
      - checkout
      - run:
          name: build
          command: |
            rm -rf public
            git clone git@github.com:ted027/ted027.github.io public
            hugo
      - run:
          name: push
          command: |
            cd public
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="rebuilding site `date`"
            git commit -m "$msg"
            git push origin master
