version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/hugo
    steps:
      - run:
          name: install hugo
          command: |
            mkdir $HOME/src
            cd $HOME/src
            git clone https://github.com/gohugoio/hugo.git
            cd hugo
            go install
      - checkout
      - run:
          name: build
          command: |
            rm -rf public/*
            hugo
      - save_cache:
          key: hugo-cache-public-{{ epoch }}
          paths:
            - /go/src/github.com/public
  
  deploy:
    machine:
      enabled: true
    working_directory: ~/hugo/public
    steps:
      - run:
          command: |
            git init
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            git add --all
            msg="rebuilding site `date`"
            git commit -m "$msg"
            git push git@github.com:ted027/ted027.github.io

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build