version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com
    steps:
      - checkout
      - run:
          name: update
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git clone https://github.com/gohugoio/hugo.git
            cd hugo
            go install
            cd -
      - run:
          name: build
          command: ./deploy.sh